---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: tools
spec:
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
      pre.hook.backup.velero.io/container: fsfreeze
      pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/config"]'
      post.hook.backup.velero.io/container: fsfreeze
      post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/config"]'
    additionalContainers:
      fsfreeze:
        name: fsfreeze
        image: ghcr.io/k8s-at-home/fsfreeze:v2.37-r0
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          privileged: true
    image:
      repository: filebrowser/filebrowser
      tag: v2.21.1
    nameOverride: filebrowser
    env:
      FB_DATABASE: "/config/filebrowser.db"
      FB_ROOT: "/media"
      FB_LOG: "stdout"
      FB_NOAUTH: "true"
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: 80
    initContainers:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "web-sync"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            #          external-dns.alpha.kubernetes.io/target: "traefik.${SECRET_DOMAIN_CASA}"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
          - host: "filebrowser.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "filebrowser.${SECRET_DOMAIN_CASA}"
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config-v2
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/media
        mountPath: /media
        readOnly: true
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
