---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  storageClassName: media
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${STORAGE_ADDRESS}"
    path: /storage/media
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 30Ti
