---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    # nodeSelector:
    #   kubernetes.io/hostname: nuc1
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.6.2
    env:
      TZ: "${TZ}"
    envFrom:
      - secretRef:
          name: home-assistant
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
          - host: "hass.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.${SECRET_DOMAIN_CASA}"
      local:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: "traefik.${SECRET_DOMAIN_CASA}"
        hosts:
          - host: "hass.local.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.local.${SECRET_DOMAIN_CASA}"
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v4
        volumeMounts:
          - name: config
            mountPath: /config
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/backups/softwarrself/home-assistant
        mountPath: /config/backups
        readOnly: false
      attachments:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/cameras-attachments
        mountPath: /camera-detection-attachments
    podAnnotations:
      secret.reloader.stakater.com/reload: "home-assistant"
    addons:
      codeserver:
        enabled: true
        image:
          repository: docker.io/codercom/code-server
          tag: 4.4.0
        env:
          TZ: "${TZ}"
        git:
          deployKeySecret: code-server
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
          hosts:
            - host: &host "hass-config.${SECRET_DOMAIN_CASA}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
