---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.linkerd.io/stable
      chart: linkerd2
      version: 2.11.0
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: linkerd-certs
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM
  values:
    webhookFailurePolicy: Fail
    enablePodAntiAffinity: true
    installNamespace: false
    identity:
      issuer:
        crtExpiry: "2021-10-20T10:29:51Z"
