---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.18
    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 3
    env:
      TZ: "${TZ}"
    metrics:
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
    service:
      main:
        ports:
          http:
            port: 4000
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_BLOCKY_ADDRESS}"
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    config: |
      upstream:
        externalResolvers:
        - tcp-tls:${SECRET_CLOUDFLARE_GATEWAY}:853
      caching:
        prefetching: true
      clientLookup:
        upstream: tcp+udp:${GATEWAY_ADDRESS}
      blocking:
        refreshPeriod: 600
        blackLists:
          ads:
          # https://energized.pro/
          - https://energized.pro/ultimate/formats/filter
          - https://energized.pro/extensions/regional/formats/filter
          # https://oisd.nl/
          - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
          # filter
          - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
          # adaway
          - https://adaway.org/hosts.txt
          # windows
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
          # yoyo
          - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
          # smarttv
          - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
          # consoles
          - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
          # someonewhocares
          - https://someonewhocares.org/hosts/zero/hosts
          # RO adblock
          - https://raw.githubusercontent.com/tcptomato/ROad-Block/master/road-block-filters.txt
          # stevenBlack
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          # cameleon
          - http://sysctl.org/cameleon/hosts
          # disconnect
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      conditional:
        mapping:
          home.wifi: tcp+udp:${GATEWAY_ADDRESS}
          home.iot: tcp+udp:${GATEWAY_ADDRESS}
          home.lan: tcp+udp:${GATEWAY_ADDRESS}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    prometheus:
      serviceMonitor:
        enabled: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
