---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backups-media-pv
spec:
  storageClassName: nfs-backup-media
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${TRUENAS_VM_ADDRESS}"
    path: /mnt/nvme/backups/pvc
#  mountOptions:
#    - nfsvers=4.2
#    - tcp
#    - intr
#    - hard
#    - noatime
#    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backups-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-backup-media
  resources:
    requests:
      storage: 2Ti
