---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.30.2
    objstoreConfig:
      type: s3
      config:
#        signature_version2: true
        insecure: false
    queryFrontend:
      enabled: false
    query:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      replicaLabel: ["__replica__"] # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.replicaExternalLabelName`
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: &host "thanos-query.${SECRET_DOMAIN_INTERNAL}"
        tls: true
        extraTls:
          - hosts:
              - *host
    bucketweb:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: &host "thanos-bucketweb.${SECRET_DOMAIN_INTERNAL}"
        tls: true
        extraTls:
          - hosts:
              - *host
    compactor:
      enabled: true
      extraFlags: ["--compact.concurrency", "4"]
      retentionResolutionRaw: 7d
      retentionResolution5m: 14d
      retentionResolution1h: 30d
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: &host "thanos-compactor.${SECRET_DOMAIN_INTERNAL}"
        tls: true
        extraTls:
          - hosts:
              - *host
      persistence:
        enabled: true
        size: 20Gi
    storegateway:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: &host "thanos-storegateway.${SECRET_DOMAIN_INTERNAL}"
        tls: true
        extraTls:
          - hosts:
              - *host
      persistence:
        enabled: true
        size: 20Gi
    ruler:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      dnsDiscovery:
        enabled: true
      alertmanagers: ["http://kube-prometheus-stack-alertmanager:9093"]
      # Breaks any metric that has an existing "cluster" label on a metric
      # clusterName: home # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.externalLabels.cluster`
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: &host "thanos-ruler.${SECRET_DOMAIN_INTERNAL}"
        tls: true
        extraTls:
          - hosts:
              - *host
      persistence:
        enabled: true
        size: 20Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  valuesFrom:
    - targetPath: objstoreConfig.config.bucket
      kind: Secret
      name: thanos-secret
      valuesKey: BUCKET_NAME
    - targetPath: objstoreConfig.config.endpoint
      kind: Secret
      name: thanos-secret
      valuesKey: BUCKET_HOST
    - targetPath: objstoreConfig.config.region
      kind: Secret
      name: thanos-secret
      valuesKey: BUCKET_REGION
    - targetPath: objstoreConfig.config.access_key
      kind: Secret
      name: thanos-secret
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: objstoreConfig.config.secret_key
      kind: Secret
      name: thanos-secret
      valuesKey: AWS_SECRET_ACCESS_KEY
