---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.26.1
    env:
      TZ: "Europe/Bucharest"
    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
        - host: "plex-requests.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "plex-requests.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v3
        mountPath: /app/config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 750Mi
