---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: home
spec:
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.4.54
    podSecurityContext:
      fsGroup: 2000
    timezone: Europe/Bucharest
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_UNIFI_ADDR}"
        ports:
          # -- Configure Web interface + API port
          # @default -- See values.yaml
          http:
            port: 8443
          # -- Configure Controller port used for device command/control
          # @default -- See values.yaml
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          # -- Configure Captive Portal HTTP port
          # @default -- See values.yaml
          portal-http:
            enabled: false
            port: 8880
            protocol: HTTP
          # -- Configure Captive Portal HTTPS port
          # @default -- See values.yaml
          portal-https:
            enabled: true
            port: 8843
            protocol: HTTPS
          # -- Configure Speedtest port (used for UniFi mobile speed test)
          # @default -- See values.yaml
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          # -- Configure STUN port
          # @default -- See values.yaml
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          # -- Configure remote syslog port
          # @default -- See values.yaml
          syslog:
            enabled: false
            port: 5514
            protocol: UDP
          # -- Configure device discovery port
          # @default -- See values.yaml
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
    ingress:
      portal:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "traefik.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          traefik.ingress.kubernetes.io/service.serversscheme: https
        hosts:
        - host: "unifi.${SECRET_DOMAIN}"
          paths:
          - ## Path. Helm template can be passed.
            path: /
            ## Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              ## Overrides the service name reference for this path
              name: unifi
              ## Overrides the service port reference for this path
              port: 8443
        tls:
        - hosts:
          - "unifi.${SECRET_DOMAIN}"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        existingClaim: unifi-config-v3
        mountPath: /unifi
    jvmMaxHeapSize: 8192M
    resources:
      limits:
        cpu: 2000m
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 128Mi
