---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pv-backup
  namespace: backup
spec:
  schedule: "5 4 * * 4" # 04:05 Thu
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 300
      template:
        spec:
          serviceAccountName: sa-pv-backup
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          containers:
            - name: pv-backup
              image: ghcr.io/k8s-at-home/kubectl:v1.23.6
              command:
                - "/bin/sh"
              args:
                - "-c"
                - "sleep 9999"
              env:
                - name: DESTINATION_NAMESPACE
                  value: backup
                - name: DESTINATION_PVC_NAME
                  value: nfs-backups-pvc
              volumeMounts:
                - mountPath: /scripts/pv-backup.sh
                  name: pv-backup
                  subPath: pv-backup.sh
          volumes:
            - name: pv-backup
              configMap:
                defaultMode: 0777
                name: pv-backup
