---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app frigate
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 100
  upgrade:
    remediation:
      retries: 100
  values:
    fullnameOverride: *app
    image:
      repository: docker.io/blakeblackshear/frigate
      tag: 0.10.1-amd64
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: &port 5000
    probes:
      liveness:
        enabled: false
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness:
        enabled: false
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      startup:
        enabled: false
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          failureThreshold: 30
          periodSeconds: 10
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
          - host: "frigate.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "frigate.${SECRET_DOMAIN_CASA}"
    persistence:
      data:
        enabled: true
        existingClaim: frigate-config-v2
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: config.yaml
        mountPath: /config/config.yml
        readOnly: true
      media:
        enabled: true
        type: nfs
        server: "${TRUENAS_VM_ADDRESS}"
        path: /mnt/tank/frigate
        mountPath: /media
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        mountPath: /dev/shm

    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
        gpu.intel.com/i915: "1"
      limits:
        memory: 16Gi
        gpu.intel.com/i915: "1"
