---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup
spec:
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.24.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
    - name: velero-plugin-for-gcp
      image: velero/velero-plugin-for-gcp:v1.3.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    deployRestic: false
    configuration:
      provider: gcp
      backupStorageLocation:
        name: gcp
        default: true
        provider: velero.io/gcp
        bucket: "${SECRET_VELERO_BACKUP_BUCKET}"
    credentials:
      existingSecret: gcp-credentials
    schedules:
      backup-all:
        disabled: false
        schedule: "0 16 * * *"
        useOwnerReferencesInBackup: true
        template:
          ttl: "240h"
