---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mylar
  namespace: media
spec:
  releaseName: mylar
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mylar
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/mylar3
      tag: version-v0.5.7
    env:
      TZ: ${TZ}
    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
          - host: "mylar.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "mylar.${SECRET_DOMAIN_CASA}"
    persistence:
      config:
        enabled: true
        existingClaim: mylar-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/media/comics
        mountPath: /media/comics
      nzbget-downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/nvme/nzbget-downloads
        mountPath: /nzbget-downloads
    resources:
      limits:
        cpu: 1.2
        memory: 8Gi
      requests:
        cpu: 50m
        memory: 256Mi
