---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recipes
  namespace: home
spec:
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vabene1111/recipes
      tag: 1.2.4
    nameOverride: recipes
    env:
      TIMEZONE: "${TZ}"
      ALLOWED_HOSTS: "*"
      ENABLE_SIGNUP: 1
      ENABLE_METRICS: 1
      DEBUG: 0
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: homelab-pgsql-pooler.databases
      POSTGRES_PORT: 5432
      POSTGRES_DB: recipes
      POSTGRES_USER: recipes
      REVERSE_PROXY_AUTH: 1
      PROXY_HEADER: Cf-Access-Authenticated-User-Email

      S3_BUCKET_NAME: recipes-mediafiles
      S3_REGION_NAME: eu-central-1
      S3_ENDPOINT_URL: https://s3.eu-central-1.wasabisys.com

      # Email Settings, see https://docs.djangoproject.com/en/3.2/ref/settings/#email-host
      # Required for email confirmation and password reset (automatically activates if host is set)
      EMAIL_HOST: smtp.sendgrid.net
      EMAIL_PORT: 465
      EMAIL_HOST_USER: apikey
      # EMAIL_USE_TLS=1
      EMAIL_USE_SSL: 1
      #DEFAULT_FROM_EMAIL: # email sender address (default 'webmaster@localhost')
      # ACCOUNT_EMAIL_SUBJECT_PREFIX= # prefix used for account related emails (default "[Tandoor Recipes] ")
    envFrom:
      - secretRef:
          name: recipes
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
          - host: "recipes.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8080
        tls:
          - hosts:
              - "recipes.${SECRET_DOMAIN_CASA}"
    podAnnotations:
      secret.reloader.stakater.com/reload: "recipes"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
